// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEoZP77CggA35DzYYpL573dn88Y5xAQFM',
    appId: '1:733455179171:web:6669d123b438009bdb0e16',
    messagingSenderId: '733455179171',
    projectId: 'scamshield-ai-7f3c4',
    authDomain: 'scamshield-ai-7f3c4.firebaseapp.com',
    storageBucket: 'scamshield-ai-7f3c4.firebasestorage.app',
    measurementId: 'G-Y9JVBJGHB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9awTVGSFiUauaj-QZj_1n3JjHmZmCK8',
    appId: '1:733455179171:android:49799eb50f4c057cdb0e16',
    messagingSenderId: '733455179171',
    projectId: 'scamshield-ai-7f3c4',
    storageBucket: 'scamshield-ai-7f3c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzI9ErD6BWPpw1bD6tBzldcB7sqo6H04s',
    appId: '1:733455179171:ios:dcb72cfa8a2c8242db0e16',
    messagingSenderId: '733455179171',
    projectId: 'scamshield-ai-7f3c4',
    storageBucket: 'scamshield-ai-7f3c4.firebasestorage.app',
    iosBundleId: 'com.example.scamShield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzI9ErD6BWPpw1bD6tBzldcB7sqo6H04s',
    appId: '1:733455179171:ios:dcb72cfa8a2c8242db0e16',
    messagingSenderId: '733455179171',
    projectId: 'scamshield-ai-7f3c4',
    storageBucket: 'scamshield-ai-7f3c4.firebasestorage.app',
    iosBundleId: 'com.example.scamShield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEoZP77CggA35DzYYpL573dn88Y5xAQFM',
    appId: '1:733455179171:web:a20fbc296365f990db0e16',
    messagingSenderId: '733455179171',
    projectId: 'scamshield-ai-7f3c4',
    authDomain: 'scamshield-ai-7f3c4.firebaseapp.com',
    storageBucket: 'scamshield-ai-7f3c4.firebasestorage.app',
    measurementId: 'G-ZVWH1WZEJ0',
  );
}
